---
driver:
  name: vagrant
driver_config:
  use_vagrant_berkshelf_plugin: true

provisioner:
  name: chef_solo

platforms:
<%
  chef_versions = %w(
    11.0.0
    latest
  )

  # non RHEL OS's
  test_platforms = %w(
    ubuntu-12.04
    ubuntu-14.04
    debian-6.0.10
    freebsd-10.3
  )

  # RHEL OS's
  test_platforms_rhel = %w(
      centos-6.8
      centos-7.1
  )
%>

<% test_platforms.product(chef_versions).each do |platform_version, chef_version| %>
  - name: <%= platform_version %>-<%= chef_version %>
    driver_config:
      box: bento/<%= platform_version %>
      require_chef_omnibus: <%= chef_version %>
<% end %>

<% test_platforms_rhel.product(chef_versions).each do |platform_version, chef_version| %>
  - name: <%= platform_version %>-<%= chef_version %>
    driver_config:
      box: bento/<%= platform_version %>
      require_chef_omnibus: <%= chef_version %>
    run_list:
      - recipe[yum-epel::default]
      - recipe[yum-remi::default]
<% end %>

suites:
  - name: default
    run_list:
      - recipe[redisio::default]
      - recipe[redisio::enable]
    attributes:
     redisio:
        servers:
          - port: 6379
          - port: 16379
            name: 'savetest'
            save: "a\nb\nc"
  - name: redis-package
    run_list:
      - recipe[redisio::default]
      - recipe[redisio::enable]
    attributes:
     redisio:
        servers:
          - port: 6379
        package_install: true
        version:
    excludes:
    <% # OS's to exclude
      test_platforms = %w(
          ubuntu-12.04
          debian-6.0.10
        )

      test_platforms.product(chef_versions).each do |platform_version, chef_version|
    %>
      - <%= platform_version %>-<%= chef_version %>
    <% end %>
  - name: sentinel
    run_list:
      - recipe[redisio::default]
      - recipe[redisio::enable]
      - recipe[redisio::sentinel]
      - recipe[redisio::sentinel_enable]
    attributes:
     redisio:
        servers:
          - port: 6379
  - name: multisentinel
    run_list:
      - recipe[redisio::default]
      - recipe[redisio::enable]
      - recipe[redisio::sentinel]
      - recipe[redisio::sentinel_enable]
    attributes:
     redisio:
        servers:
          - port: 6379
          - port: 6380
        sentinels:
          -
            name: 'cluster'
            sentinel_port: 26379
            masters:
              -
                name: 'sentinel6379'
                master_name: 'master6379'
                master_ip: '127.0.0.1'
                master_port: 6379
              -
                name: 'sentinel6380'
                master_name: 'master6380'
                master_ip: '127.0.0.1'
                master_port: 6380
